package syncer

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/terrapilot/terrapilot/internal/descriptor"
)

const header = "# Generated by terrapilot — do not edit\n"

// Sync renders all imported templates for every stack and writes the output
// files into each stack's directory.
func Sync(stacks []*descriptor.Stack) error {
	for _, s := range stacks {
		if len(s.Imports) == 0 {
			continue
		}

		ctx, err := descriptor.ResolveTemplateContext(s)
		if err != nil {
			return fmt.Errorf("stack %q: resolving template context: %w", s.Name, err)
		}

		for _, tplPath := range s.Imports {
			abs := descriptor.ResolvePath(tplPath, s.Dir, s.Root)
			if err := renderTemplate(abs, s.Dir, ctx); err != nil {
				return fmt.Errorf("stack %q: %w", s.Name, err)
			}
		}
	}
	return nil
}

func renderTemplate(tplPath, stackDir string, ctx map[string]string) error {
	src, err := os.ReadFile(tplPath)
	if err != nil {
		return fmt.Errorf("reading template %s: %w", tplPath, err)
	}

	// expose each key as a function so templates can write ${region} directly
	funcMap := make(template.FuncMap, len(ctx))
	for k, v := range ctx {
		v := v // capture
		funcMap[k] = func() string { return v }
	}

	tmpl, err := template.New(filepath.Base(tplPath)).
		Delims("${", "}").
		Funcs(funcMap).
		Parse(string(src))
	if err != nil {
		return fmt.Errorf("parsing template %s: %w", tplPath, err)
	}

	var buf bytes.Buffer
	buf.WriteString(header)
	if err := tmpl.Execute(&buf, nil); err != nil {
		return fmt.Errorf("rendering template %s: %w", tplPath, err)
	}

	outName := outputName(filepath.Base(tplPath))
	outPath := filepath.Join(stackDir, outName)

	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}

	fmt.Printf("[terrapilot] synced %s → %s\n", tplPath, outPath)
	return nil
}

// outputName strips the .tpl suffix to get the destination filename.
// e.g. "backend.tf.tpl" → "backend.tf"
func outputName(base string) string {
	return strings.TrimSuffix(base, ".tpl")
}
